//HintName: Endpoint.generated.cs
#nullable enable

// <auto-generated>
// This is a MinimalApiBuilder source generated generated file.
// </auto-generated>

using Microsoft.AspNetCore.Builder;
using MinimalApiBuilder;
using FluentValidation;
using FluentValidation.Results;

namespace Features
{
    public partial class Endpoint1 : IEndpoint
    {
        public static Delegate _auto_generated_Handler { get; } = Handle;
        public static void _auto_generated_Configure(RouteHandlerBuilder builder)
        {
        }
    }
}
namespace Features
{
    public partial class Endpoint2 : IEndpoint
    {
        public static Delegate _auto_generated_Handler { get; } = HandleAsync;
        public static void _auto_generated_Configure(RouteHandlerBuilder builder)
        {
        }
    }
}
