//HintName: DependencyInjection.generated.cs
#nullable enable

// <auto-generated>
// This is a MinimalApiBuilder source generated file.
// </auto-generated>

using FluentValidation;
using Microsoft.Extensions.DependencyInjection;

namespace MinimalApiBuilder
{
    public static class DependencyInjection
    {
        public static IServiceCollection AddMinimalApiBuilderEndpoints(this IServiceCollection services)
        {
            services.AddScoped<global::Features.Endpoint1>();
            return services;
        }
    }
}
