using System.Text;

namespace MinimalApiBuilder.Generator.Entities;

internal sealed class SourceBuilder
{
    private const int IndentSize = 4;

    private readonly StringBuilder _builder = new(@"#nullable enable

// <auto-generated>
// This is a MinimalApiBuilder source generated generated file.
// </auto-generated>

");

    private int _indent;

    public Block OpenBlock(string value)
    {
        _builder.Append(' ', _indent);
        _builder.AppendLine(value);
        _builder.Append(' ', _indent);
        _builder.AppendLine("{");
        IncreaseIndent();
        return new Block(this);
    }

    public void AppendLine(string value)
    {
        _builder.Append(' ', _indent);
        _builder.AppendLine(value);
    }

    private void IncreaseIndent()
    {
        _indent += IndentSize;
    }

    private void DecreaseIndent()
    {
        _indent -= IndentSize;
    }

    public override string ToString() => _builder.ToString();

    internal readonly struct Block
    {
        private readonly SourceBuilder _builder;

        public Block(SourceBuilder builder)
        {
            _builder = builder;
        }

        public void Close()
        {
            _builder.DecreaseIndent();
            _builder.AppendLine("}");
        }

        public void Close(string value)
        {
            _builder.DecreaseIndent();
            _builder.AppendLine($"}} // {value}");
        }
    }
}
