using Microsoft.AspNetCore.Builder;

namespace MinimalApiBuilder;

/// <summary>
/// Marker interface for the partial classes generated by the minimal API builder generator.
/// </summary>
public interface IMinimalApiBuilderEndpoint
{
#pragma warning disable CA1707
#pragma warning disable IDE1006
    /// <summary>
    /// The static request handler, which the minimal API builder generator will populate.
    /// </summary>
    static abstract Delegate _auto_generated_Handler { get; }

    /// <summary>
    /// The auto generated <see cref="Configure(RouteHandlerBuilder)" />, which the minimal API builder generator will populate.
    /// </summary>
    static abstract void _auto_generated_Configure(RouteHandlerBuilder builder);
#pragma warning restore IDE1006
#pragma warning restore CA1707

    /// <summary>
    /// Configure the <see cref="RouteHandlerBuilder" /> of this endpoint.
    /// </summary>
    /// <param name="builder">
    /// A <see cref="RouteHandlerBuilder" /> that can be used to further customize the endpoint.
    /// </param>
    static abstract void Configure(RouteHandlerBuilder builder);
}
