using System.Text;
using Microsoft.CodeAnalysis;
using MinimalApiBuilder.Generator.Common;
using MinimalApiBuilder.Generator.Entities;

namespace MinimalApiBuilder.Generator.CodeGeneration;

internal abstract class SourceBuilder
{
    private const int IndentSize = 4;
    private readonly StringBuilder _builder = new(@"// <auto-generated>
// This is a MinimalApiBuilder source generated file.
// </auto-generated>

#nullable enable

");
    private int _indent;

    protected SourceBuilder()
    {
        Options = default;
    }

    protected SourceBuilder(GeneratorOptions options)
    {
        Options = options;
    }

    protected GeneratorOptions Options { get; set; }

    protected ICollection<Diagnostic> Diagnostics { get; } = new List<Diagnostic>();

    public virtual void AddSource(SourceProductionContext context)
    {
        foreach (Diagnostic diagnostic in Diagnostics)
        {
            context.ReportDiagnostic(diagnostic);
        }
    }

    public sealed override string ToString() => _builder.ToString();

    protected IDisposable OpenBlock(string value)
    {
        WriteBlockStart(value);
        return new Disposable(() =>
        {
            DecreaseIndent();
            AppendLine("}");
        });
    }

    protected IDisposable OpenBlock(params string[] values)
    {
        for (int i = 0; i < values.Length - 1; i++)
        {
            AppendLine(values[i]);
        }

        return OpenBlock(values[values.Length - 1]);
    }

    protected IDisposable OpenBlockExtra(string afterClose, string value)
    {
        WriteBlockStart(value);
        return new Disposable(() =>
        {
            DecreaseIndent();
            AppendLine($"}}{afterClose}");
        });
    }

    protected IDisposable OpenBlockExtra(string afterClose, params string[] values)
    {
        for (int i = 0; i < values.Length - 1; i++)
        {
            AppendLine(values[i]);
        }

        return OpenBlockExtra(afterClose, values[values.Length - 1]);
    }

    protected void AppendLine()
    {
        _builder.AppendLine();
    }

    protected void AppendLine(string value)
    {
        _builder.Append(' ', _indent);
        _builder.AppendLine(value);
    }

    private void IncreaseIndent()
    {
        _indent += IndentSize;
    }

    private void DecreaseIndent()
    {
        _indent -= IndentSize;
    }

    private void WriteBlockStart(string value)
    {
        _builder.Append(' ', _indent);
        _builder.AppendLine(value);
        _builder.Append(' ', _indent);
        _builder.AppendLine("{");
        IncreaseIndent();
    }
}
