//HintName: DependencyInjection.g.cs
// <auto-generated>
// This is a MinimalApiBuilder source generated file.
// </auto-generated>

#nullable enable

using FluentValidation;
using Microsoft.Extensions.DependencyInjection;

namespace MinimalApiBuilder
{
    public static class DependencyInjection
    {
        public static IServiceCollection AddMinimalApiBuilderEndpoints(this IServiceCollection services)
        {
            services.AddScoped<global::Features.Endpoint1>();
            services.AddTransient<IValidator<global::Features.Request>, global::Features.SyncValidator>();
            services.AddScoped<IValidator<global::Features.Parameters>, global::Features.AsyncValidator>();
            return services;
        }
    }
}
