//HintName: ConfigureEndpoints.Specialization.g.cs
// <auto-generated>
// This is a MinimalApiBuilder source generated file.
// </auto-generated>

#nullable enable

namespace MinimalApiBuilder
{
    internal static partial class ConfigureEndpoints
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("MinimalApiBuilder.Generator", "1.0.0.0")]
        public static void Configure(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder b0)
        {
            global::E._auto_generated_Configure(b0);
            global::E.Configure(b0);
        }
    }
}
