//HintName: ConfigureEndpoints.Specialization.g.cs
// <auto-generated>
// This is a MinimalApiBuilder source generated file.
// </auto-generated>

#nullable enable

namespace MinimalApiBuilder
{
    internal static partial class ConfigureEndpoints
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("MinimalApiBuilder.Generator", "1.0.0.0")]
        public static void Configure(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder b0, global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder b1)
        {
            global::E1._auto_generated_Configure(b0);
            global::E1.Configure(b0);
            global::E2._auto_generated_Configure(b1);
            global::E2.Configure(b1);
        }
    }
}
