//HintName: MapEndpointsExtensions.g.cs
// <auto-generated>
// This is a MinimalApiBuilder source generated file.
// </auto-generated>

#nullable enable

namespace MinimalApiBuilder
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("MinimalApiBuilder.Generator", "1.0.0.0")]
    internal static class MapEndpointsExtensions
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("MinimalApiBuilder.Generator", "1.0.0.0")]
        public static global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder Map<TEndpoint>(this global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder endpoints, [global::System.Diagnostics.CodeAnalysis.StringSyntaxAttribute("Route")] string pattern, global::E1? _ = default) where TEndpoint : global::E1
        {
            global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder = global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.Map(endpoints, pattern, global::E1.Handle);
            global::E1._auto_generated_Configure(builder);
            global::E1.Configure(builder);
            return builder;
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("MinimalApiBuilder.Generator", "1.0.0.0")]
        public static global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder MapMethods<TEndpoint>(this global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder endpoints, [global::System.Diagnostics.CodeAnalysis.StringSyntaxAttribute("Route")] string pattern, global::System.Collections.Generic.IEnumerable<string> httpMethods, global::E1? _ = default) where TEndpoint : global::E1
        {
            global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder = global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapMethods(endpoints, pattern, httpMethods, global::E1.Handle);
            global::E1._auto_generated_Configure(builder);
            global::E1.Configure(builder);
            return builder;
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("MinimalApiBuilder.Generator", "1.0.0.0")]
        public static global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder MapGet<TEndpoint>(this global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder endpoints, [global::System.Diagnostics.CodeAnalysis.StringSyntaxAttribute("Route")] string pattern, global::E1? _ = default) where TEndpoint : global::E1
        {
            global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder = global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapGet(endpoints, pattern, global::E1.Handle);
            global::E1._auto_generated_Configure(builder);
            global::E1.Configure(builder);
            return builder;
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("MinimalApiBuilder.Generator", "1.0.0.0")]
        public static global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder MapPost<TEndpoint>(this global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder endpoints, [global::System.Diagnostics.CodeAnalysis.StringSyntaxAttribute("Route")] string pattern, global::E1? _ = default) where TEndpoint : global::E1
        {
            global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder = global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapPost(endpoints, pattern, global::E1.Handle);
            global::E1._auto_generated_Configure(builder);
            global::E1.Configure(builder);
            return builder;
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("MinimalApiBuilder.Generator", "1.0.0.0")]
        public static global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder MapPut<TEndpoint>(this global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder endpoints, [global::System.Diagnostics.CodeAnalysis.StringSyntaxAttribute("Route")] string pattern, global::E1? _ = default) where TEndpoint : global::E1
        {
            global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder = global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapPut(endpoints, pattern, global::E1.Handle);
            global::E1._auto_generated_Configure(builder);
            global::E1.Configure(builder);
            return builder;
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("MinimalApiBuilder.Generator", "1.0.0.0")]
        public static global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder MapDelete<TEndpoint>(this global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder endpoints, [global::System.Diagnostics.CodeAnalysis.StringSyntaxAttribute("Route")] string pattern, global::E1? _ = default) where TEndpoint : global::E1
        {
            global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder = global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapDelete(endpoints, pattern, global::E1.Handle);
            global::E1._auto_generated_Configure(builder);
            global::E1.Configure(builder);
            return builder;
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("MinimalApiBuilder.Generator", "1.0.0.0")]
        public static global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder MapPatch<TEndpoint>(this global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder endpoints, [global::System.Diagnostics.CodeAnalysis.StringSyntaxAttribute("Route")] string pattern, global::E1? _ = default) where TEndpoint : global::E1
        {
            global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder = global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapPatch(endpoints, pattern, global::E1.Handle);
            global::E1._auto_generated_Configure(builder);
            global::E1.Configure(builder);
            return builder;
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("MinimalApiBuilder.Generator", "1.0.0.0")]
        public static global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder Map<TEndpoint>(this global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder endpoints, [global::System.Diagnostics.CodeAnalysis.StringSyntaxAttribute("Route")] string pattern, global::E2? _ = default) where TEndpoint : global::E2
        {
            global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder = global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.Map(endpoints, pattern, global::E2.Handle);
            global::E2._auto_generated_Configure(builder);
            global::E2.Configure(builder);
            return builder;
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("MinimalApiBuilder.Generator", "1.0.0.0")]
        public static global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder MapMethods<TEndpoint>(this global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder endpoints, [global::System.Diagnostics.CodeAnalysis.StringSyntaxAttribute("Route")] string pattern, global::System.Collections.Generic.IEnumerable<string> httpMethods, global::E2? _ = default) where TEndpoint : global::E2
        {
            global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder = global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapMethods(endpoints, pattern, httpMethods, global::E2.Handle);
            global::E2._auto_generated_Configure(builder);
            global::E2.Configure(builder);
            return builder;
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("MinimalApiBuilder.Generator", "1.0.0.0")]
        public static global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder MapGet<TEndpoint>(this global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder endpoints, [global::System.Diagnostics.CodeAnalysis.StringSyntaxAttribute("Route")] string pattern, global::E2? _ = default) where TEndpoint : global::E2
        {
            global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder = global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapGet(endpoints, pattern, global::E2.Handle);
            global::E2._auto_generated_Configure(builder);
            global::E2.Configure(builder);
            return builder;
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("MinimalApiBuilder.Generator", "1.0.0.0")]
        public static global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder MapPost<TEndpoint>(this global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder endpoints, [global::System.Diagnostics.CodeAnalysis.StringSyntaxAttribute("Route")] string pattern, global::E2? _ = default) where TEndpoint : global::E2
        {
            global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder = global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapPost(endpoints, pattern, global::E2.Handle);
            global::E2._auto_generated_Configure(builder);
            global::E2.Configure(builder);
            return builder;
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("MinimalApiBuilder.Generator", "1.0.0.0")]
        public static global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder MapPut<TEndpoint>(this global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder endpoints, [global::System.Diagnostics.CodeAnalysis.StringSyntaxAttribute("Route")] string pattern, global::E2? _ = default) where TEndpoint : global::E2
        {
            global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder = global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapPut(endpoints, pattern, global::E2.Handle);
            global::E2._auto_generated_Configure(builder);
            global::E2.Configure(builder);
            return builder;
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("MinimalApiBuilder.Generator", "1.0.0.0")]
        public static global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder MapDelete<TEndpoint>(this global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder endpoints, [global::System.Diagnostics.CodeAnalysis.StringSyntaxAttribute("Route")] string pattern, global::E2? _ = default) where TEndpoint : global::E2
        {
            global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder = global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapDelete(endpoints, pattern, global::E2.Handle);
            global::E2._auto_generated_Configure(builder);
            global::E2.Configure(builder);
            return builder;
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("MinimalApiBuilder.Generator", "1.0.0.0")]
        public static global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder MapPatch<TEndpoint>(this global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder endpoints, [global::System.Diagnostics.CodeAnalysis.StringSyntaxAttribute("Route")] string pattern, global::E2? _ = default) where TEndpoint : global::E2
        {
            global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder = global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapPatch(endpoints, pattern, global::E2.Handle);
            global::E2._auto_generated_Configure(builder);
            global::E2.Configure(builder);
            return builder;
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("MinimalApiBuilder.Generator", "1.0.0.0")]
        public static global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder Map<TEndpoint>(this global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder endpoints, [global::System.Diagnostics.CodeAnalysis.StringSyntaxAttribute("Route")] string pattern, global::E3? _ = default) where TEndpoint : global::E3
        {
            global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder = global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.Map(endpoints, pattern, global::E3.Handle);
            global::E3._auto_generated_Configure(builder);
            global::E3.Configure(builder);
            return builder;
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("MinimalApiBuilder.Generator", "1.0.0.0")]
        public static global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder MapMethods<TEndpoint>(this global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder endpoints, [global::System.Diagnostics.CodeAnalysis.StringSyntaxAttribute("Route")] string pattern, global::System.Collections.Generic.IEnumerable<string> httpMethods, global::E3? _ = default) where TEndpoint : global::E3
        {
            global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder = global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapMethods(endpoints, pattern, httpMethods, global::E3.Handle);
            global::E3._auto_generated_Configure(builder);
            global::E3.Configure(builder);
            return builder;
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("MinimalApiBuilder.Generator", "1.0.0.0")]
        public static global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder MapGet<TEndpoint>(this global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder endpoints, [global::System.Diagnostics.CodeAnalysis.StringSyntaxAttribute("Route")] string pattern, global::E3? _ = default) where TEndpoint : global::E3
        {
            global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder = global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapGet(endpoints, pattern, global::E3.Handle);
            global::E3._auto_generated_Configure(builder);
            global::E3.Configure(builder);
            return builder;
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("MinimalApiBuilder.Generator", "1.0.0.0")]
        public static global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder MapPost<TEndpoint>(this global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder endpoints, [global::System.Diagnostics.CodeAnalysis.StringSyntaxAttribute("Route")] string pattern, global::E3? _ = default) where TEndpoint : global::E3
        {
            global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder = global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapPost(endpoints, pattern, global::E3.Handle);
            global::E3._auto_generated_Configure(builder);
            global::E3.Configure(builder);
            return builder;
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("MinimalApiBuilder.Generator", "1.0.0.0")]
        public static global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder MapPut<TEndpoint>(this global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder endpoints, [global::System.Diagnostics.CodeAnalysis.StringSyntaxAttribute("Route")] string pattern, global::E3? _ = default) where TEndpoint : global::E3
        {
            global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder = global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapPut(endpoints, pattern, global::E3.Handle);
            global::E3._auto_generated_Configure(builder);
            global::E3.Configure(builder);
            return builder;
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("MinimalApiBuilder.Generator", "1.0.0.0")]
        public static global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder MapDelete<TEndpoint>(this global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder endpoints, [global::System.Diagnostics.CodeAnalysis.StringSyntaxAttribute("Route")] string pattern, global::E3? _ = default) where TEndpoint : global::E3
        {
            global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder = global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapDelete(endpoints, pattern, global::E3.Handle);
            global::E3._auto_generated_Configure(builder);
            global::E3.Configure(builder);
            return builder;
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("MinimalApiBuilder.Generator", "1.0.0.0")]
        public static global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder MapPatch<TEndpoint>(this global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder endpoints, [global::System.Diagnostics.CodeAnalysis.StringSyntaxAttribute("Route")] string pattern, global::E3? _ = default) where TEndpoint : global::E3
        {
            global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder = global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapPatch(endpoints, pattern, global::E3.Handle);
            global::E3._auto_generated_Configure(builder);
            global::E3.Configure(builder);
            return builder;
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("MinimalApiBuilder.Generator", "1.0.0.0")]
        public static global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder Map<TEndpoint>(this global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder endpoints, [global::System.Diagnostics.CodeAnalysis.StringSyntaxAttribute("Route")] string pattern, global::E4? _ = default) where TEndpoint : global::E4
        {
            global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder = global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.Map(endpoints, pattern, global::E4.Handle);
            global::E4._auto_generated_Configure(builder);
            global::E4.Configure(builder);
            return builder;
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("MinimalApiBuilder.Generator", "1.0.0.0")]
        public static global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder MapMethods<TEndpoint>(this global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder endpoints, [global::System.Diagnostics.CodeAnalysis.StringSyntaxAttribute("Route")] string pattern, global::System.Collections.Generic.IEnumerable<string> httpMethods, global::E4? _ = default) where TEndpoint : global::E4
        {
            global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder = global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapMethods(endpoints, pattern, httpMethods, global::E4.Handle);
            global::E4._auto_generated_Configure(builder);
            global::E4.Configure(builder);
            return builder;
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("MinimalApiBuilder.Generator", "1.0.0.0")]
        public static global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder MapGet<TEndpoint>(this global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder endpoints, [global::System.Diagnostics.CodeAnalysis.StringSyntaxAttribute("Route")] string pattern, global::E4? _ = default) where TEndpoint : global::E4
        {
            global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder = global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapGet(endpoints, pattern, global::E4.Handle);
            global::E4._auto_generated_Configure(builder);
            global::E4.Configure(builder);
            return builder;
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("MinimalApiBuilder.Generator", "1.0.0.0")]
        public static global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder MapPost<TEndpoint>(this global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder endpoints, [global::System.Diagnostics.CodeAnalysis.StringSyntaxAttribute("Route")] string pattern, global::E4? _ = default) where TEndpoint : global::E4
        {
            global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder = global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapPost(endpoints, pattern, global::E4.Handle);
            global::E4._auto_generated_Configure(builder);
            global::E4.Configure(builder);
            return builder;
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("MinimalApiBuilder.Generator", "1.0.0.0")]
        public static global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder MapPut<TEndpoint>(this global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder endpoints, [global::System.Diagnostics.CodeAnalysis.StringSyntaxAttribute("Route")] string pattern, global::E4? _ = default) where TEndpoint : global::E4
        {
            global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder = global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapPut(endpoints, pattern, global::E4.Handle);
            global::E4._auto_generated_Configure(builder);
            global::E4.Configure(builder);
            return builder;
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("MinimalApiBuilder.Generator", "1.0.0.0")]
        public static global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder MapDelete<TEndpoint>(this global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder endpoints, [global::System.Diagnostics.CodeAnalysis.StringSyntaxAttribute("Route")] string pattern, global::E4? _ = default) where TEndpoint : global::E4
        {
            global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder = global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapDelete(endpoints, pattern, global::E4.Handle);
            global::E4._auto_generated_Configure(builder);
            global::E4.Configure(builder);
            return builder;
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("MinimalApiBuilder.Generator", "1.0.0.0")]
        public static global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder MapPatch<TEndpoint>(this global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder endpoints, [global::System.Diagnostics.CodeAnalysis.StringSyntaxAttribute("Route")] string pattern, global::E4? _ = default) where TEndpoint : global::E4
        {
            global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder = global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapPatch(endpoints, pattern, global::E4.Handle);
            global::E4._auto_generated_Configure(builder);
            global::E4.Configure(builder);
            return builder;
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("MinimalApiBuilder.Generator", "1.0.0.0")]
        public static global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder Map<TEndpoint>(this global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder endpoints, [global::System.Diagnostics.CodeAnalysis.StringSyntaxAttribute("Route")] string pattern, global::E5? _ = default) where TEndpoint : global::E5
        {
            global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder = global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.Map(endpoints, pattern, global::E5.Handle);
            global::E5._auto_generated_Configure(builder);
            global::E5.Configure(builder);
            return builder;
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("MinimalApiBuilder.Generator", "1.0.0.0")]
        public static global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder MapMethods<TEndpoint>(this global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder endpoints, [global::System.Diagnostics.CodeAnalysis.StringSyntaxAttribute("Route")] string pattern, global::System.Collections.Generic.IEnumerable<string> httpMethods, global::E5? _ = default) where TEndpoint : global::E5
        {
            global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder = global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapMethods(endpoints, pattern, httpMethods, global::E5.Handle);
            global::E5._auto_generated_Configure(builder);
            global::E5.Configure(builder);
            return builder;
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("MinimalApiBuilder.Generator", "1.0.0.0")]
        public static global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder MapGet<TEndpoint>(this global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder endpoints, [global::System.Diagnostics.CodeAnalysis.StringSyntaxAttribute("Route")] string pattern, global::E5? _ = default) where TEndpoint : global::E5
        {
            global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder = global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapGet(endpoints, pattern, global::E5.Handle);
            global::E5._auto_generated_Configure(builder);
            global::E5.Configure(builder);
            return builder;
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("MinimalApiBuilder.Generator", "1.0.0.0")]
        public static global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder MapPost<TEndpoint>(this global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder endpoints, [global::System.Diagnostics.CodeAnalysis.StringSyntaxAttribute("Route")] string pattern, global::E5? _ = default) where TEndpoint : global::E5
        {
            global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder = global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapPost(endpoints, pattern, global::E5.Handle);
            global::E5._auto_generated_Configure(builder);
            global::E5.Configure(builder);
            return builder;
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("MinimalApiBuilder.Generator", "1.0.0.0")]
        public static global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder MapPut<TEndpoint>(this global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder endpoints, [global::System.Diagnostics.CodeAnalysis.StringSyntaxAttribute("Route")] string pattern, global::E5? _ = default) where TEndpoint : global::E5
        {
            global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder = global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapPut(endpoints, pattern, global::E5.Handle);
            global::E5._auto_generated_Configure(builder);
            global::E5.Configure(builder);
            return builder;
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("MinimalApiBuilder.Generator", "1.0.0.0")]
        public static global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder MapDelete<TEndpoint>(this global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder endpoints, [global::System.Diagnostics.CodeAnalysis.StringSyntaxAttribute("Route")] string pattern, global::E5? _ = default) where TEndpoint : global::E5
        {
            global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder = global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapDelete(endpoints, pattern, global::E5.Handle);
            global::E5._auto_generated_Configure(builder);
            global::E5.Configure(builder);
            return builder;
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("MinimalApiBuilder.Generator", "1.0.0.0")]
        public static global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder MapPatch<TEndpoint>(this global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder endpoints, [global::System.Diagnostics.CodeAnalysis.StringSyntaxAttribute("Route")] string pattern, global::E5? _ = default) where TEndpoint : global::E5
        {
            global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder = global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapPatch(endpoints, pattern, global::E5.Handle);
            global::E5._auto_generated_Configure(builder);
            global::E5.Configure(builder);
            return builder;
        }
    }
}
