namespace MinimalApiBuilder.Generator.Common;

internal static class Sources
{
    public const string Header = """
        // <auto-generated>
        // This is a MinimalApiBuilder source generated file.
        // </auto-generated>

        #nullable enable

        """;

    public static readonly string GeneratedCodeAttribute = $"""
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("{typeof(MinimalApiBuilderGenerator).Assembly.GetName().Name}", "{typeof(MinimalApiBuilderGenerator).Assembly.GetName().Version}")]
        """;

    public static readonly string ConfigureEndpoints = $$"""
        {{Header}}
        namespace MinimalApiBuilder
        {
            {{GeneratedCodeAttribute}}
            internal static partial class {{nameof(ConfigureEndpoints)}}
            {
                {{GeneratedCodeAttribute}}
                public static void Configure(params {{Fqn.RouteHandlerBuilder}}[] builders)
                { }
            }
        }
        """;
}
