using System.Reflection;

namespace MinimalApiBuilder.Generator.Common;

internal static class Sources
{
    private static readonly AssemblyName s_assemblyName = typeof(MinimalApiBuilderGenerator).Assembly.GetName();

    public const string Header = """
        // <auto-generated>
        // This is a MinimalApiBuilder source generated file.
        // </auto-generated>

        #nullable enable


        """;

    public static readonly string GeneratedCodeAttribute = $"""
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("{s_assemblyName.Name}", "{s_assemblyName.Version}")]
        """;

    public static readonly string ConfigureEndpoints = $$"""
        {{Header}}namespace MinimalApiBuilder.Generator
        {
            {{GeneratedCodeAttribute}}
            internal static partial class {{nameof(ConfigureEndpoints)}}
            {
                {{GeneratedCodeAttribute}}
                public static void Configure(params {{Fqn.RouteHandlerBuilder}}[] builders)
                { }
            }
        }
        """;
}
