//HintName: Endpoint.generated.cs
#nullable enable

// <auto-generated>
// This is a MinimalApiBuilder source generated file.
// </auto-generated>

using Microsoft.AspNetCore.Builder;
using MinimalApiBuilder;
using FluentValidation;
using FluentValidation.Results;

namespace Features
{
    public partial class Endpoint1 : IEndpoint
    {
        public static Delegate _auto_generated_Handler { get; } = Handle;
        public static void _auto_generated_Configure(RouteHandlerBuilder builder)
        {
            builder.WithName(Name);
        }
        private const string Name = nameof(Endpoint1);
    }
}
